### ISSUE TITLE
node - Cannot find module

### ISSUE THREAD

**Issue by PatricNox** [vestusola/vue-chat-emoji#6]
I cannot seem to use this package in my vue project. 

I also run typescript, which is something that this package has no support for.

```
33:38 Cannot find module 'vue-chat-emoji'.
> 33 | import { VueChatEmoji, emojis } from 'vue-chat-emoji'
```

**Reproduction**

> $ yarn add vue-chat-emoji
> $ yarn install && yarn serve
> 33:38 Cannot find module 'vue-chat-emoji'.

**Comment by PatricNox** [comment]
This works: 

> import { VueChatEmoji, emojis } from 'vue-chat-emoji/dist/vue-chat-emoji.esm.js'

**Comment by vestusola** [comment]
Thanks. I will work towards that.

**Comment by PatricNox** [comment]
@vestusola one of the binary files (dist/*.esm|umd|min.js) should be set as the main prop so this wouldn't be neccessary.

**Comment by PatricNox** [comment]
@vestusola  This is fixed, works well now.

However, latest release is broken:

![image](https://user-images.githubusercontent.com/31646653/95423316-2b5d6f80-0941-11eb-9c63-d657e768e736.png)

**Comment by vestusola** [comment]
> @vestusola This is fixed, works well now.
> 
> However, latest release is broken:
> 
> ![image](https://user-images.githubusercontent.com/31646653/95423316-2b5d6f80-0941-11eb-9c63-d657e768e736.png)

Is it via import or using the CDN link?
If you import the package, remember to require the stylesheet file

**Comment by PatricNox** [comment]
@vestusola  CDN link is broken (404) and im using import, i simply updated package.json to use the latest release rather than my fork, and this happened

i believe its unrelated to the stylesheets since it works on my fork which is using 1.1.26

**Comment by vestusola** [comment]
@PatricNox I tried using the latest version 1.1.27 and it works well on my side.
![emoji](https://user-images.githubusercontent.com/31238687/95437260-b2641500-094c-11eb-80bd-aa8ae60c3508.PNG)

**Comment by vestusola** [comment]
> @PatricNox I tried using the latest version 1.1.27 and it works well on my side.
> ![emoji](https://user-images.githubusercontent.com/31238687/95437260-b2641500-094c-11eb-80bd-aa8ae60c3508.PNG)

I mean the CDN link

**Comment by PatricNox** [comment]
@vestusola  Ah!

Since I use typescript, I had to import the stylesheet by manually copying the css contents. 
I forgot to do this on the new release, my bad.

Everything works flawlessly, amazing!
